#ifndef DNS_ERRORCODE_H
#define DNS_ERRORCODE_H

enum errcode_t {
    UDP_RECV_ERR=-1,

    DNS_RESOLVE_ERR=-20,
    DNS_LABEL_LEN_ERR=-21,

    DNS_RCODE_ERR=-30,
    PACKET_SESSION_ID_MISS_ERR=-32,
    PACKET_GROUP_ID_MISS_ERR=-32,
    PACKET_DATA_ID_MISS_ERR=-33,
    PACKET_TYPE_MISS_ERR=-34,


    BASE36_ERR=-100

};

#endif //DNS_ERRORCODE_H
